//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NativeMock.Analyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NativeMock.Analyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The signature of a native mock interface method must match with the signature of the declaring method..
        /// </summary>
        internal static string DeclaringFunctionSignatureMismatchDescription {
            get {
                return ResourceManager.GetString("DeclaringFunctionSignatureMismatchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The signature of the native mock interface method &apos;{0}&apos; did not match its declaring method.
        /// </summary>
        internal static string DeclaringFunctionSignatureMismatchMessageFormat {
            get {
                return ResourceManager.GetString("DeclaringFunctionSignatureMismatchMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature mismatch between native mock interface method and declaring method.
        /// </summary>
        internal static string DeclaringFunctionSignatureMismatchTitle {
            get {
                return ResourceManager.GetString("DeclaringFunctionSignatureMismatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No suitable declaring method was found. Make sure the name and module match the provided name and module in the DllImportAttribute..
        /// </summary>
        internal static string NoDeclaringTypeDescription {
            get {
                return ResourceManager.GetString("NoDeclaringTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No declaring method was found for the native mock interface method &apos;{0}&apos;.
        /// </summary>
        internal static string NoDeclaringTypeMessageFormat {
            get {
                return ResourceManager.GetString("NoDeclaringTypeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No declaring method found for native mock interface method.
        /// </summary>
        internal static string NoDeclaringTypeTitle {
            get {
                return ResourceManager.GetString("NoDeclaringTypeTitle", resourceCulture);
            }
        }
    }
}
